services:
    backend:
        container_name: backend-chatPDF
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env.dev
        environment:
            - DB_HOST=db
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis

    db:
        container_name: db
        image: pgvector/pgvector:pg16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: chatPDF_production
        volumes:
            - pgChatPDF:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    pgChatPDF:
    redis_data:
